{% set name = "lifton" %}
{% set version = "1.0.2" %}
{% set sha256 = "6cee1ad0961ac38c79d7d3c389624321698506614cf572328c412e7cea37f4b5" %}

package:
  name: lifton
  version: '{{version}}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{sha256}}'

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3
    - pip

  run:
    - python >=3
    - numpy >=1.22.0
    - biopython >=1.76
    - parasail >=1.2.4
    - intervaltree >=3.1.0
    - interlap >=0.2.6
    - networkx >=2.4
    - pyfaidx >=0.5.8
    - pysam >=0.19.1
    - gffutils >=0.10.1
    - ujson >=3.2.0
    - cigar >=0.1.3

test:
  imports:
    - lifton

about:
  home: https://github.com/Kuanhao-Chao/Lifton
  license: GPL3
  license_family: GPL3
  summary: "Combining DNA and protein alignments to improve genome annotation with LiftOn"
  description: |
    Combining DNA and protein alignments to improve genome annotation with LiftOn
  doc_url: https://github.com/Kuanhao-Chao/Lifton
  dev_url: https://github.com/Kuanhao-Chao/Lifton

extra:
  recipe-maintainers:
    - kuanhao-chao


