{% set name = "splam" %}
{% set ucname = "splam" %}
{% set version = "0.2.15" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ ucname }}-{{ version }}.tar.gz"
  sha256: "656ed5fe31d1d3053e322d38e23004e1d50074e6d9b83a9aaa94ff81ad6140c8"

build:
  number: 0
  skip: True  # [py27 or py < 37]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - torch
    - pybedtools
    - gffutils
    - numpy

test:
  commands:
    - run_test.py

about:
  home: "https://github.com/Kuanhao-Chao/splam"
  license: MIT
  license_family: MIT
  summary: "Deep learning-based splicing predictor."
  doc_url: "https://github.com/Kuanhao-Chao/splam/blob/main/README.md"
  dev_url: "https://github.com/Kuanhao-Chao/splam/"

extra:
  recipe-maintainers:
    - Kuanhao-Chao
  identifiers:
    - https://github.com/Kuanhao-Chao/splam
